parser_outputs=['MCRA_TUEF_SEGMENT_HEADER','MCRA_TUEF_PW_SEGMENT','MCRA_TUEF_NA_SEGMENT','MCRA_TUEF_AL_SEGMENT','MCRA_TUEF_AD_SEGMENT','MCRA_TUEF_SA_SEGMENT','MCRA_TUEF_PH_SEGMENT','MCRA_TUEF_PF_SEGMENT','MCRA_TUEF_SC_SEGMENT','MCRA_TUEF_SM_SEGMENT','MCRA_TUEF_WA_SEGMENT','MCRA_TUEF_CS_SEGMENT','MCRA_TUEF_EX_SEGMENT','MCRA_TUEF_AC_SEGMENT','MCRA_TUEF_VE_SEGMENT','MCRA_TUEF_EQ_SEGMENT','MCRA_TUEF_VS_SEGMENT','MCRA_TUEF_EN_SEGMENT','MCRA_TUEF_WR_SEGMENT','MCRA_TUEF_PT_SEGMENT','MCRA_TUEF_NT_SEGMENT','MCRA_TUEF_PN_SEGMENT','MCRA_TUEF_EA_SEGMENT','MCRA_TUEF_WS_SEGMENT','MCRA_TUEF_BD_SEGMENT','MCRA_TUEF_BN_SEGMENT','MCRA_TUEF_BE_SEGMENT','MCRA_TUEF_BA_SEGMENT','MCRA_TUEF_BM_SEGMENT','MCRA_TUEF_BG_SEGMENT','MCRA_TUEF_BJ_SEGMENT','MCRA_TUEF_TR_SEGMENT','MCRA_TUEF_SS_SEGMENT','MCRA_TUEF_CV_SEGMENT','MCRA_TUEF_ST_SEGMENT','MCRA_TUEF_PC_SEGMENT','MCRA_TUEF_SE_SEGMENT','MCRA_TUEF_AV_SEGMENT','MCRA_TUEF_AT_SEGMENT','MCRA_TUEF_UR_SEGMENT']
tables_tag={
          "HeaderResponseSegment": "MCRA_TUEF_SEGMENT_HEADER",
          "PasswordSegment": "MCRA_TUEF_PW_SEGMENT",
          "NameSegment": "MCRA_TUEF_NA_SEGMENT",
          "AliasNameSegment": "MCRA_TUEF_AL_SEGMENT",
          "AddressSegment": "MCRA_TUEF_AD_SEGMENT",
          "StructuredAddressAlertFeaturesSegment": "MCRA_TUEF_SA_SEGMENT",
          "ContactNumberSegment": "MCRA_TUEF_PH_SEGMENT",
          "ContactNumberAlertFeaturesSegment": "MCRA_TUEF_PF_SEGMENT",
          "ScoreSegment": "MCRA_TUEF_SC_SEGMENT",
	  "SuperSetSegment": "MCRA_TUEF_SS_SEGMENT",
          "CreditVisionSegment": "MCRA_TUEF_CV_SEGMENT",
          "StressTestSegment": "MCRA_TUEF_ST_SEGMENT",
          "PremiumCustomizedAttributesSegment": "MCRA_TUEF_PC_SEGMENT",
          "SegmentationSegment": "MCRA_TUEF_SE_SEGMENT",
          "AddressVerificationSegment": "MCRA_TUEF_AV_SEGMENT",
          "AddressVerificationSegment2.0": "MCRA_TUEF_AT_SEGMENT",
          "UserReferenceErrorSegment":"MCRA_TUEF_UR_SEGMENT"
}
